In [5]:
'''list components....input version'''
nums=[int(input(f"enter number{i+1}:")) for i in range(5)]
print(nums)

enter number1: 2
enter number2: 3
enter number3: 4
enter number4: 2
enter number5: 3


[2, 3, 4, 2, 3]


In [9]:
n=[int(x) for x in input("Enter numbers with space:").split()]
print(n)

Enter nums with space: 66 633 3 67 976 3 00


[66, 633, 3, 67, 976, 3, 0]


In [1]:
#nested lc...loop within loop in a single lc
n=int(input("enter table size:"))
table=[[i*j for j  in range(1,n+1)] for i in range(1,n+1)]
print("Tables of math")
for row in table:
    print(row)

enter table size: 5


Tables of math
[1, 2, 3, 4, 5]
[2, 4, 6, 8, 10]
[3, 6, 9, 12, 15]
[4, 8, 12, 16, 20]
[5, 10, 15, 20, 25]


In [5]:
'''create a nxn matrix with manual input numbers 
    input separated spaces
    print all the rows in lc only'''
nums=input("Enter 9 rows with spces").split()
if len(nums)!=9:
    print("Enter exactly 9 numbers:")
else:
    numbers=[int(x) for x in nums]
    matrix=[[numbers[i*3+j] for j in range(3)] for i in range(3)]
for r in matrix:
    print(r)

Enter 9 rows with spces 1 2 3 4 5 6 7 8 9


[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [11]:
#transpose of a matrix...
nums=input("Enter 9 rows with spces").split()
if len(nums)!=9:
    print("Enter exactly 9 numbers:")
else:
    numbers=[int(x) for x in nums]
    matrix=[[numbers[i*3+j] for j in range(3)] for i in range(3)]
    transpose=[[matrix[i][j] for i in range(3)] for j in range(3)]
for r in matrix:
    print(r)
for r in transpose:
    print(r)

Enter 9 rows with spces 23 1 3 543 564 3 44  5 1


[23, 1, 3]
[543, 564, 3]
[44, 5, 1]
[23, 543, 44]
[1, 564, 5]
[3, 3, 1]


In [ ]:
n=int(input("Ener size:"))
num=[int(x) for x in input("Enter nummbers").split()[:n*n]]
matrix=[[num[i*n+j] for j in range(n)] for i in range(n)]
for k in matrix:
    print(k)
flat=[k for r in matrix for k in r]
print(flat)

In [7]:
'''Code to consider a lc : to calculate square of 16 values as non 
    matrix and print the list of  squares is each row
    3=9 values 1 2 3 4 5 6 7 8 9
    1 2 3    [1,4,9]
    4 5 6    [16,25,36]
    7 8 9    [49,64,81]

#(
    n = 4
num = [int(x) for x in input("Enter 16 numbers (space-separated): ").split()[:n*n]]
squared_values = [x**2 for x in num]
print("List of squares, grouped into rows:")
for i in range(n):
    row_start = i * n
    row_end = (i + 1) * n
    print(squared_values[row_start:row_end])
)#

SyntaxError: incomplete input (3054341445.py, line 1)

In [5]:
n = int(input("Enter the size:"))
num = [int(x) for x in input("Enter {n} numbers (space-separated): ").split()[:n*n]]
squared_values = [x**2 for x in num]
print("List of squares, grouped into rows:")
for i in range(n):
    row_start = i * n
    row_end = (i + 1) * n
    print(squared_values[row_start:row_end])


Enter the size: 3
Enter {n} numbers (space-separated):  1 2 3 4 4 5 6 7 8 9 101


List of squares, grouped into rows:
[1, 4, 9]
[16, 16, 25]
[36, 49, 64]


In [17]:
#odd number
numbers = input('Enter numbers separated by spaces: ')
number_list = [int(num) for num in numbers.split()]
odd_numbers_list = [num for num in number_list if num % 2 != 0]
print("Odd numbers in the list:", odd_numbers_list)


Enter numbers separated by spaces:  1 2 3 5 4 56 


Odd numbers in the list: [1, 3, 5]


In [21]:
#Even number
numbers = input('Enter numbers separated by spaces: ')
number_list = [int(num) for num in numbers.split()]
even_numbers_list = [num for num in number_list if num % 2 ==0]
print("Even numbers in the list:", even_numbers_list)


Enter numbers separated by spaces:  1 2 23 4 5 6 87


Even numbers in the list: [2, 4, 6]


In [23]:
import numpy as np

def generate_binary_matrix(n):
    if n % 2 != 0:
        raise ValueError("Please provide an even number.")
    # Random 0-1 matrix of size n x n
    matrix = np.random.randint(0, 2, size=(n, n))
    return matrix

even_number = 6  # You can change this to any even number
result = generate_binary_matrix(even_number)
print(result)


[[1 1 1 0 1 1]
 [1 0 0 1 1 0]
 [0 1 1 0 0 1]
 [0 0 1 1 0 0]
 [1 1 0 1 0 1]
 [0 0 1 0 0 1]]


In [ ]:
#prime numbbers+